language: ruby

before_install: gem update bundler
bundler_args: --without development

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ruby-head

branches:
  only:
    - master
    - develop

matrix:
  allow_failures:
    - rvm: 2.1.0
    - rvm: ruby-head
  fast_finish: true

script: bundle exec rake travis
